spring:
  application:
    name: Keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/tutoring3
          jwk-set-url: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 8081
  
jwt:
  auth:
    converter: 
      resource-id: tutoring3-resource-server
      principle-attribute: preferred_username